FROM ubuntu:22.04

# Instala siege
RUN apt-get update && \
    apt-get install -y siege && \
    apt-get clean

# Copia configuración personalizada y el script de entrada
RUN mkdir -p /root/.siege
COPY entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
