services:
  webserv:
    build: ./webserv
    container_name: webserv
    expose:
      - "8081"
      - "8082"
    networks:
      - webserv_net
    volumes:
      - ./logs:/logs

  siege:
    build: ./siege
    container_name: siege
    depends_on:
      - webserv
    networks:
      - webserv_net
    entrypoint: >
      /bin/bash -c "
        echo '[+] Esperando a que webserv esté disponible...';
        until curl -s http://webserv:8081 > /dev/null; do sleep 1; done;
        echo '[+] Webserv activo, lanzando pruebas de carga...';
        siege -c 5 -t30S http://webserv:8081
        siege -c 5 -t30S http://webserv:8082"

    tty: true

networks:
  webserv_net:
    name: webserv_net
    driver: bridge
    external: false

# docker-compose up -d --build   
# docker logs siege
# valgrind --tool=memcheck --leak-check=full --track-origins=yes --show-leak-kinds=all --error-exitcode=42 ./webserv default.conf 