FROM ubuntu:22.04

# Instala valgrind
RUN apt-get update && \
    apt-get install -y valgrind && \
    apt-get clean

# WORKDIR /app

# Copia tu servidor y la configuración
COPY webserv ./webserv
COPY default.conf ./default.conf
COPY ./entrypoint.sh /entrypoint.sh
COPY ./www ./www

RUN chmod +x /entrypoint.sh
RUN chmod +x ./webserv
EXPOSE 8081
# Ejecuta el servidor bajo Valgrind
CMD ["valgrind", "--tool=memcheck", "--leak-check=full", \
     "--track-origins=yes", "--show-leak-kinds=all", \
     "--error-exitcode=42", "./webserv", "default.conf"]

